import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class FormDataService {

  formData = new BehaviorSubject([]);

  //a predefined default forms list
  defaultFormsArrays: any = [
    {
      "name": "MyForm1",
      "components": [
        {
          "label": "Text Field",
          "labelPosition": "top",
          "placeholder": "",
          "description": "",
          "tooltip": "",
          "prefix": "",
          "suffix": "",
          "widget": {
            "type": "input"
          },
          "inputMask": "",
          "allowMultipleMasks": false,
          "customClass": "",
          "tabindex": "",
          "autocomplete": "",
          "hidden": false,
          "hideLabel": false,
          "showWordCount": false,
          "showCharCount": false,
          "mask": false,
          "autofocus": false,
          "spellcheck": true,
          "disabled": false,
          "tableView": true,
          "modalEdit": false,
          "multiple": false,
          "defaultValue": "",
          "persistent": true,
          "inputFormat": "plain",
          "protected": false,
          "dbIndex": false,
          "case": "",
          "encrypted": false,
          "redrawOn": "",
          "clearOnHide": true,
          "customDefaultValue": "",
          "calculateValue": "",
          "calculateServer": false,
          "allowCalculateOverride": false,
          "validateOn": "change",
          "validate": {
            "required": false,
            "pattern": "",
            "customMessage": "",
            "custom": "",
            "customPrivate": false,
            "json": "",
            "minLength": "",
            "maxLength": "",
            "strictDateValidation": false,
            "multiple": false,
            "unique": false
          },
          "unique": false,
          "errorLabel": "",
          "key": "textField",
          "tags": [],
          "properties": {},
          "conditional": {
            "show": null,
            "when": null,
            "eq": "",
            "json": ""
          },
          "customConditional": "",
          "logic": [],
          "attributes": {},
          "overlay": {
            "style": "",
            "page": "",
            "left": "",
            "top": "",
            "width": "",
            "height": ""
          },
          "type": "textfield",
          "input": true,
          "refreshOn": "",
          "dataGridLabel": false,
          "inputType": "text",
          "id": "ej9b9mk"
        },
        {
          "label": "Text Field",
          "labelPosition": "top",
          "placeholder": "",
          "description": "",
          "tooltip": "",
          "prefix": "",
          "suffix": "",
          "widget": {
            "type": "input"
          },
          "inputMask": "",
          "allowMultipleMasks": false,
          "customClass": "",
          "tabindex": "",
          "autocomplete": "",
          "hidden": false,
          "hideLabel": false,
          "showWordCount": false,
          "showCharCount": false,
          "mask": false,
          "autofocus": false,
          "spellcheck": true,
          "disabled": false,
          "tableView": true,
          "modalEdit": false,
          "multiple": false,
          "defaultValue": "",
          "persistent": true,
          "inputFormat": "plain",
          "protected": false,
          "dbIndex": false,
          "case": "",
          "encrypted": false,
          "redrawOn": "",
          "clearOnHide": true,
          "customDefaultValue": "",
          "calculateValue": "",
          "calculateServer": false,
          "allowCalculateOverride": false,
          "validateOn": "change",
          "validate": {
            "required": false,
            "pattern": "",
            "customMessage": "",
            "custom": "",
            "customPrivate": false,
            "json": "",
            "minLength": "",
            "maxLength": "",
            "strictDateValidation": false,
            "multiple": false,
            "unique": false
          },
          "unique": false,
          "errorLabel": "",
          "key": "textField1",
          "tags": [],
          "properties": {},
          "conditional": {
            "show": null,
            "when": null,
            "eq": "",
            "json": ""
          },
          "customConditional": "",
          "logic": [],
          "attributes": {},
          "overlay": {
            "style": "",
            "page": "",
            "left": "",
            "top": "",
            "width": "",
            "height": ""
          },
          "type": "textfield",
          "input": true,
          "refreshOn": "",
          "dataGridLabel": false,
          "inputType": "text",
          "id": "ek05gh"
        },
        {
          "type": "button",
          "label": "Submit",
          "key": "submit",
          "size": "md",
          "block": false,
          "action": "submit",
          "disableOnInvalid": true,
          "theme": "primary",
          "input": true,
          "placeholder": "",
          "prefix": "",
          "customClass": "",
          "suffix": "",
          "multiple": false,
          "defaultValue": null,
          "protected": false,
          "unique": false,
          "persistent": false,
          "hidden": false,
          "clearOnHide": true,
          "refreshOn": "",
          "redrawOn": "",
          "tableView": false,
          "modalEdit": false,
          "dataGridLabel": true,
          "labelPosition": "top",
          "description": "",
          "errorLabel": "",
          "tooltip": "",
          "hideLabel": false,
          "tabindex": "",
          "disabled": false,
          "autofocus": false,
          "dbIndex": false,
          "customDefaultValue": "",
          "calculateValue": "",
          "calculateServer": false,
          "widget": {
            "type": "input"
          },
          "attributes": {},
          "validateOn": "change",
          "validate": {
            "required": false,
            "custom": "",
            "customPrivate": false,
            "strictDateValidation": false,
            "multiple": false,
            "unique": false
          },
          "conditional": {
            "show": null,
            "when": null,
            "eq": ""
          },
          "overlay": {
            "style": "",
            "left": "",
            "top": "",
            "width": "",
            "height": ""
          },
          "allowCalculateOverride": false,
          "encrypted": false,
          "showCharCount": false,
          "showWordCount": false,
          "properties": {},
          "allowMultipleMasks": false,
          "leftIcon": "",
          "rightIcon": "",
          "id": "ekx9xlo"
        }
      ]
    },
    {
      "name": "MyForm2",
      "components": [
        {
          "label": "Text Field",
          "labelPosition": "top",
          "placeholder": "",
          "description": "",
          "tooltip": "",
          "prefix": "",
          "suffix": "",
          "widget": {
            "type": "input"
          },
          "inputMask": "",
          "allowMultipleMasks": false,
          "customClass": "",
          "tabindex": "",
          "autocomplete": "",
          "hidden": false,
          "hideLabel": false,
          "showWordCount": false,
          "showCharCount": false,
          "mask": false,
          "autofocus": false,
          "spellcheck": true,
          "disabled": false,
          "tableView": true,
          "modalEdit": false,
          "multiple": false,
          "defaultValue": "",
          "persistent": true,
          "inputFormat": "plain",
          "protected": false,
          "dbIndex": false,
          "case": "",
          "encrypted": false,
          "redrawOn": "",
          "clearOnHide": true,
          "customDefaultValue": "",
          "calculateValue": "",
          "calculateServer": false,
          "allowCalculateOverride": false,
          "validateOn": "change",
          "validate": {
            "required": false,
            "pattern": "",
            "customMessage": "",
            "custom": "",
            "customPrivate": false,
            "json": "",
            "minLength": "",
            "maxLength": "",
            "strictDateValidation": false,
            "multiple": false,
            "unique": false
          },
          "unique": false,
          "errorLabel": "",
          "key": "textField",
          "tags": [],
          "properties": {},
          "conditional": {
            "show": null,
            "when": null,
            "eq": "",
            "json": ""
          },
          "customConditional": "",
          "logic": [],
          "attributes": {},
          "overlay": {
            "style": "",
            "page": "",
            "left": "",
            "top": "",
            "width": "",
            "height": ""
          },
          "type": "textfield",
          "input": true,
          "refreshOn": "",
          "dataGridLabel": false,
          "inputType": "text",
          "id": "e5kr79r"
        },
        {
          "label": "Number",
          "labelPosition": "top",
          "placeholder": "",
          "description": "",
          "tooltip": "",
          "prefix": "",
          "suffix": "",
          "widget": {
            "type": "input"
          },
          "customClass": "",
          "tabindex": "",
          "autocomplete": "",
          "hidden": false,
          "hideLabel": false,
          "mask": false,
          "autofocus": false,
          "disabled": false,
          "tableView": false,
          "modalEdit": false,
          "multiple": false,
          "persistent": true,
          "delimiter": false,
          "requireDecimal": false,
          "inputFormat": "plain",
          "protected": false,
          "dbIndex": false,
          "encrypted": false,
          "redrawOn": "",
          "clearOnHide": true,
          "customDefaultValue": "",
          "calculateValue": "",
          "calculateServer": false,
          "allowCalculateOverride": false,
          "validateOn": "change",
          "validate": {
            "required": false,
            "customMessage": "",
            "custom": "",
            "customPrivate": false,
            "json": "",
            "min": "",
            "max": "",
            "strictDateValidation": false,
            "multiple": false,
            "unique": false,
            "step": "any",
            "integer": ""
          },
          "errorLabel": "",
          "key": "number",
          "tags": [],
          "properties": {},
          "conditional": {
            "show": null,
            "when": null,
            "eq": "",
            "json": ""
          },
          "customConditional": "",
          "logic": [],
          "attributes": {},
          "overlay": {
            "style": "",
            "page": "",
            "left": "",
            "top": "",
            "width": "",
            "height": ""
          },
          "type": "number",
          "input": true,
          "unique": false,
          "refreshOn": "",
          "dataGridLabel": false,
          "showCharCount": false,
          "showWordCount": false,
          "allowMultipleMasks": false,
          "id": "ezskfbs",
          "defaultValue": null
        },
        {
          "type": "button",
          "label": "Submit",
          "key": "submit",
          "size": "md",
          "block": false,
          "action": "submit",
          "disableOnInvalid": true,
          "theme": "primary",
          "input": true,
          "placeholder": "",
          "prefix": "",
          "customClass": "",
          "suffix": "",
          "multiple": false,
          "defaultValue": null,
          "protected": false,
          "unique": false,
          "persistent": false,
          "hidden": false,
          "clearOnHide": true,
          "refreshOn": "",
          "redrawOn": "",
          "tableView": false,
          "modalEdit": false,
          "dataGridLabel": true,
          "labelPosition": "top",
          "description": "",
          "errorLabel": "",
          "tooltip": "",
          "hideLabel": false,
          "tabindex": "",
          "disabled": false,
          "autofocus": false,
          "dbIndex": false,
          "customDefaultValue": "",
          "calculateValue": "",
          "calculateServer": false,
          "widget": {
            "type": "input"
          },
          "attributes": {},
          "validateOn": "change",
          "validate": {
            "required": false,
            "custom": "",
            "customPrivate": false,
            "strictDateValidation": false,
            "multiple": false,
            "unique": false
          },
          "conditional": {
            "show": null,
            "when": null,
            "eq": ""
          },
          "overlay": {
            "style": "",
            "left": "",
            "top": "",
            "width": "",
            "height": ""
          },
          "allowCalculateOverride": false,
          "encrypted": false,
          "showCharCount": false,
          "showWordCount": false,
          "properties": {},
          "allowMultipleMasks": false,
          "leftIcon": "",
          "rightIcon": "",
          "id": "ehgw037"
        }
      ]
    },
    {
      "name": "LoginId",
      "components": [
        {
          "label": "User Name",
          "labelPosition": "top",
          "placeholder": "",
          "description": "",
          "tooltip": "",
          "prefix": "",
          "suffix": "",
          "widget": {
            "type": "input"
          },
          "inputMask": "",
          "allowMultipleMasks": false,
          "customClass": "",
          "tabindex": "",
          "autocomplete": "",
          "hidden": false,
          "hideLabel": false,
          "showWordCount": false,
          "showCharCount": false,
          "mask": false,
          "autofocus": false,
          "spellcheck": true,
          "disabled": false,
          "tableView": true,
          "modalEdit": false,
          "multiple": false,
          "defaultValue": "",
          "persistent": true,
          "inputFormat": "plain",
          "protected": false,
          "dbIndex": false,
          "case": "",
          "encrypted": false,
          "redrawOn": "",
          "clearOnHide": true,
          "customDefaultValue": "",
          "calculateValue": "",
          "calculateServer": false,
          "allowCalculateOverride": false,
          "validateOn": "change",
          "validate": {
            "required": false,
            "pattern": "",
            "customMessage": "",
            "custom": "",
            "customPrivate": false,
            "json": "",
            "minLength": "",
            "maxLength": "",
            "strictDateValidation": false,
            "multiple": false,
            "unique": false
          },
          "unique": false,
          "errorLabel": "",
          "key": "userName",
          "tags": [],
          "properties": {},
          "conditional": {
            "show": null,
            "when": null,
            "eq": "",
            "json": ""
          },
          "customConditional": "",
          "logic": [],
          "attributes": {},
          "overlay": {
            "style": "",
            "page": "",
            "left": "",
            "top": "",
            "width": "",
            "height": ""
          },
          "type": "textfield",
          "input": true,
          "refreshOn": "",
          "dataGridLabel": false,
          "inputType": "text",
          "id": "egyi6wy"
        },
        {
          "label": "User Password",
          "labelPosition": "top",
          "placeholder": "",
          "description": "",
          "tooltip": "",
          "prefix": "",
          "suffix": "",
          "widget": {
            "type": "input"
          },
          "customClass": "",
          "tabindex": "",
          "autocomplete": "",
          "hidden": false,
          "hideLabel": false,
          "showWordCount": false,
          "showCharCount": false,
          "mask": false,
          "autofocus": false,
          "spellcheck": true,
          "disabled": false,
          "tableView": false,
          "modalEdit": false,
          "case": "",
          "redrawOn": "",
          "clearOnHide": true,
          "calculateServer": false,
          "allowCalculateOverride": false,
          "validateOn": "change",
          "validate": {
            "required": false,
            "pattern": "",
            "customMessage": "",
            "custom": "",
            "customPrivate": false,
            "json": "",
            "minLength": "",
            "maxLength": "",
            "strictDateValidation": false,
            "multiple": false,
            "unique": false
          },
          "errorLabel": "",
          "key": "userPassword",
          "tags": [],
          "properties": {},
          "conditional": {
            "show": null,
            "when": null,
            "eq": "",
            "json": ""
          },
          "customConditional": "",
          "logic": [],
          "attributes": {},
          "overlay": {
            "style": "",
            "page": "",
            "left": "",
            "top": "",
            "width": "",
            "height": ""
          },
          "type": "password",
          "input": true,
          "multiple": false,
          "defaultValue": null,
          "protected": true,
          "unique": false,
          "persistent": true,
          "refreshOn": "",
          "dataGridLabel": false,
          "dbIndex": false,
          "customDefaultValue": "",
          "calculateValue": "",
          "encrypted": false,
          "allowMultipleMasks": false,
          "inputType": "text",
          "inputFormat": "plain",
          "inputMask": "",
          "id": "ef1vcln"
        },
        {
          "type": "button",
          "label": "Submit",
          "key": "submit",
          "size": "md",
          "block": false,
          "action": "submit",
          "disableOnInvalid": true,
          "theme": "primary",
          "input": true,
          "placeholder": "",
          "prefix": "",
          "customClass": "",
          "suffix": "",
          "multiple": false,
          "defaultValue": null,
          "protected": false,
          "unique": false,
          "persistent": false,
          "hidden": false,
          "clearOnHide": true,
          "refreshOn": "",
          "redrawOn": "",
          "tableView": false,
          "modalEdit": false,
          "dataGridLabel": true,
          "labelPosition": "top",
          "description": "",
          "errorLabel": "",
          "tooltip": "",
          "hideLabel": false,
          "tabindex": "",
          "disabled": false,
          "autofocus": false,
          "dbIndex": false,
          "customDefaultValue": "",
          "calculateValue": "",
          "calculateServer": false,
          "widget": {
            "type": "input"
          },
          "attributes": {},
          "validateOn": "change",
          "validate": {
            "required": false,
            "custom": "",
            "customPrivate": false,
            "strictDateValidation": false,
            "multiple": false,
            "unique": false
          },
          "conditional": {
            "show": null,
            "when": null,
            "eq": ""
          },
          "overlay": {
            "style": "",
            "left": "",
            "top": "",
            "width": "",
            "height": ""
          },
          "allowCalculateOverride": false,
          "encrypted": false,
          "showCharCount": false,
          "showWordCount": false,
          "properties": {},
          "allowMultipleMasks": false,
          "leftIcon": "",
          "rightIcon": "",
          "id": "ehgw037"
        }
      ]
    },
    {
      "name": "checklist1",
      "components": [
        {
          "label": "Favourite Food",
          "labelPosition": "top",
          "placeholder": "",
          "description": "",
          "tooltip": "",
          "prefix": "",
          "suffix": "",
          "widget": {
            "type": "input"
          },
          "inputMask": "",
          "allowMultipleMasks": false,
          "customClass": "",
          "tabindex": "",
          "autocomplete": "",
          "hidden": false,
          "hideLabel": false,
          "showWordCount": false,
          "showCharCount": false,
          "mask": false,
          "autofocus": false,
          "spellcheck": true,
          "disabled": false,
          "tableView": true,
          "modalEdit": false,
          "multiple": false,
          "defaultValue": "",
          "persistent": true,
          "inputFormat": "plain",
          "protected": false,
          "dbIndex": false,
          "case": "",
          "encrypted": false,
          "redrawOn": "",
          "clearOnHide": true,
          "customDefaultValue": "",
          "calculateValue": "",
          "calculateServer": false,
          "allowCalculateOverride": false,
          "validateOn": "change",
          "validate": {
            "required": false,
            "pattern": "",
            "customMessage": "",
            "custom": "",
            "customPrivate": false,
            "json": "",
            "minLength": "",
            "maxLength": "",
            "strictDateValidation": false,
            "multiple": false,
            "unique": false
          },
          "unique": false,
          "errorLabel": "",
          "key": "favouriteFood",
          "tags": [],
          "properties": {},
          "conditional": {
            "show": null,
            "when": null,
            "eq": "",
            "json": ""
          },
          "customConditional": "",
          "logic": [],
          "attributes": {},
          "overlay": {
            "style": "",
            "page": "",
            "left": "",
            "top": "",
            "width": "",
            "height": ""
          },
          "type": "textfield",
          "input": true,
          "refreshOn": "",
          "dataGridLabel": false,
          "inputType": "text",
          "id": "erfipn"
        },
        {
          "label": "Pizza",
          "description": "",
          "tooltip": "",
          "shortcut": "",
          "inputType": "checkbox",
          "customClass": "",
          "tabindex": "",
          "hidden": false,
          "hideLabel": false,
          "autofocus": false,
          "disabled": false,
          "tableView": false,
          "modalEdit": false,
          "persistent": true,
          "protected": false,
          "dbIndex": false,
          "encrypted": false,
          "redrawOn": "",
          "clearOnHide": true,
          "customDefaultValue": "",
          "calculateValue": "",
          "calculateServer": false,
          "allowCalculateOverride": false,
          "validate": {
            "required": false,
            "customMessage": "",
            "custom": "",
            "customPrivate": false,
            "json": "",
            "strictDateValidation": false,
            "multiple": false,
            "unique": false
          },
          "errorLabel": "",
          "key": "pizza",
          "tags": [],
          "properties": {},
          "conditional": {
            "show": null,
            "when": null,
            "eq": "",
            "json": ""
          },
          "customConditional": "",
          "logic": [],
          "attributes": {},
          "overlay": {
            "style": "",
            "page": "",
            "left": "",
            "top": "",
            "width": "",
            "height": ""
          },
          "type": "checkbox",
          "name": "",
          "value": "",
          "input": true,
          "placeholder": "",
          "prefix": "",
          "suffix": "",
          "multiple": false,
          "unique": false,
          "refreshOn": "",
          "dataGridLabel": true,
          "labelPosition": "right",
          "widget": null,
          "validateOn": "change",
          "showCharCount": false,
          "showWordCount": false,
          "allowMultipleMasks": false,
          "id": "eheyq2g",
          "defaultValue": false
        },
        {
          "label": "Chicken",
          "description": "",
          "tooltip": "",
          "shortcut": "",
          "inputType": "checkbox",
          "customClass": "",
          "tabindex": "",
          "hidden": false,
          "hideLabel": false,
          "autofocus": false,
          "disabled": false,
          "tableView": false,
          "modalEdit": false,
          "persistent": true,
          "protected": false,
          "dbIndex": false,
          "encrypted": false,
          "redrawOn": "",
          "clearOnHide": true,
          "customDefaultValue": "",
          "calculateValue": "",
          "calculateServer": false,
          "allowCalculateOverride": false,
          "validate": {
            "required": false,
            "customMessage": "",
            "custom": "",
            "customPrivate": false,
            "json": "",
            "strictDateValidation": false,
            "multiple": false,
            "unique": false
          },
          "errorLabel": "",
          "key": "chicken",
          "tags": [],
          "properties": {},
          "conditional": {
            "show": null,
            "when": null,
            "eq": "",
            "json": ""
          },
          "customConditional": "",
          "logic": [],
          "attributes": {},
          "overlay": {
            "style": "",
            "page": "",
            "left": "",
            "top": "",
            "width": "",
            "height": ""
          },
          "type": "checkbox",
          "name": "",
          "value": "",
          "input": true,
          "placeholder": "",
          "prefix": "",
          "suffix": "",
          "multiple": false,
          "unique": false,
          "refreshOn": "",
          "dataGridLabel": true,
          "labelPosition": "right",
          "widget": null,
          "validateOn": "change",
          "showCharCount": false,
          "showWordCount": false,
          "allowMultipleMasks": false,
          "id": "e9f432",
          "defaultValue": false
        },
        {
          "label": "Noodles",
          "description": "",
          "tooltip": "",
          "shortcut": "",
          "inputType": "checkbox",
          "customClass": "",
          "tabindex": "",
          "hidden": false,
          "hideLabel": false,
          "autofocus": false,
          "disabled": false,
          "tableView": false,
          "modalEdit": false,
          "persistent": true,
          "protected": false,
          "dbIndex": false,
          "encrypted": false,
          "redrawOn": "",
          "clearOnHide": true,
          "customDefaultValue": "",
          "calculateValue": "",
          "calculateServer": false,
          "allowCalculateOverride": false,
          "validate": {
            "required": false,
            "customMessage": "",
            "custom": "",
            "customPrivate": false,
            "json": "",
            "strictDateValidation": false,
            "multiple": false,
            "unique": false
          },
          "errorLabel": "",
          "key": "noodles",
          "tags": [],
          "properties": {},
          "conditional": {
            "show": null,
            "when": null,
            "eq": "",
            "json": ""
          },
          "customConditional": "",
          "logic": [],
          "attributes": {},
          "overlay": {
            "style": "",
            "page": "",
            "left": "",
            "top": "",
            "width": "",
            "height": ""
          },
          "type": "checkbox",
          "name": "",
          "value": "",
          "input": true,
          "placeholder": "",
          "prefix": "",
          "suffix": "",
          "multiple": false,
          "unique": false,
          "refreshOn": "",
          "dataGridLabel": true,
          "labelPosition": "right",
          "widget": null,
          "validateOn": "change",
          "showCharCount": false,
          "showWordCount": false,
          "allowMultipleMasks": false,
          "id": "evz5r77",
          "defaultValue": false
        },
        {
          "type": "button",
          "label": "Submit",
          "key": "submit",
          "size": "md",
          "block": false,
          "action": "submit",
          "disableOnInvalid": true,
          "theme": "primary",
          "input": true,
          "placeholder": "",
          "prefix": "",
          "customClass": "",
          "suffix": "",
          "multiple": false,
          "defaultValue": null,
          "protected": false,
          "unique": false,
          "persistent": false,
          "hidden": false,
          "clearOnHide": true,
          "refreshOn": "",
          "redrawOn": "",
          "tableView": false,
          "modalEdit": false,
          "dataGridLabel": true,
          "labelPosition": "top",
          "description": "",
          "errorLabel": "",
          "tooltip": "",
          "hideLabel": false,
          "tabindex": "",
          "disabled": false,
          "autofocus": false,
          "dbIndex": false,
          "customDefaultValue": "",
          "calculateValue": "",
          "calculateServer": false,
          "widget": {
            "type": "input"
          },
          "attributes": {},
          "validateOn": "change",
          "validate": {
            "required": false,
            "custom": "",
            "customPrivate": false,
            "strictDateValidation": false,
            "multiple": false,
            "unique": false
          },
          "conditional": {
            "show": null,
            "when": null,
            "eq": ""
          },
          "overlay": {
            "style": "",
            "left": "",
            "top": "",
            "width": "",
            "height": ""
          },
          "allowCalculateOverride": false,
          "encrypted": false,
          "showCharCount": false,
          "showWordCount": false,
          "properties": {},
          "allowMultipleMasks": false,
          "leftIcon": "",
          "rightIcon": "",
          "id": "ehgw037"
        }
      ]
    }
  ]
  constructor() {

    //calls initializaation method only once
    this.intializeDefault();
  }

  intializeDefault() {
    this.defaultFormsArrays.forEach(element => {
      this.formData.getValue().push(element);
    });
  }
  updateFormData(data) {
    this.formData.getValue().push({ ...data });
    console.log(this.formData.getValue());
  }
  getFormData() {
    this.formData.next(this.formData.getValue());
  }
  updateForm(oldData, newData) {
    const index = this.formData.getValue().indexOf(oldData);
    this.formData.getValue()[index] = newData;
  }
  deleteForm(data) {
    const index = this.formData.getValue().indexOf(data);
    if (index > -1) {
      this.formData.getValue().splice(index, 1);
    }
  }
}
